name: Auto Tag my Application
on:
  push:
    branches:
      - main
concurrency: production
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Minor version for each merge
      id: tag-dry-run
      uses: anothrNick/github-tag-action@1.66.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true

    - name: echo new tag
      run: |
        echo "The next tag version will be: ${{ steps.tag-dry-run.outputs.new_tag }}"
    - name: echo tag
      run: |
        echo "The current tag is: ${{ steps.tag-dry-run.outputs.tag }}"
    - name: echo part
      run: |
        echo "The version increment was: ${{ steps.tag-dry-run.outputs.part }}"

    # DO MY BUILD HERE
    # IN CASE OF FAILURE, THE STEP BELOW WILL NOT RUN.

    - name: Minor version for each merge
      id: tag-final
      uses: anothrNick/github-tag-action@1.66.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
