name: Auto Tag my Application
on:
  push:
    branches:
      - main
concurrency: production
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Prepare new tag
      id: tag-dry-run
      uses: anothrNick/github-tag-action@1.66.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true

    - name: Show new tag
      run: |
        echo "The next tag version will be: ${{ steps.tag-dry-run.outputs.new_tag }}"
        echo "The current tag is: ${{ steps.tag-dry-run.outputs.tag }}"
        echo "The version increment was: ${{ steps.tag-dry-run.outputs.part }}"

    - name: Set tag in cmade script
      run: |
        sed -i -E \
            -e 's/^set(CMADE_VERSION .*$/set(CMADE_VERSION "${{ steps.tag-dry-run.outputs.new_tag }}")/'

    - name: Set new version
      id: tag-final
      uses: anothrNick/github-tag-action@1.66.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
